#ifndef TCP_H
#define TCP_H

#include <stdint.h>
#include <stddef.h>

// This file was generated by Claude Haiku 4.5.

/**
 * Message types for master-worker communication
 */
typedef enum {
    MSG_TASK_REQUEST = 1,      // Master requests worker to compute a path
    MSG_TASK_RESPONSE = 2,     // Worker returns computed path result
    MSG_PING = 3,              // Heartbeat/keepalive message
    MSG_PONG = 4,              // Heartbeat response
    MSG_SHUTDOWN = 5,          // Signal to shutdown
    MSG_ERROR = 6              // Error message
} MessageType;

/**
 * Task request structure sent by master to worker
 */
typedef struct {
    uint32_t task_id;           // Unique task identifier
    float start_x, start_y;     // Start coordinates
    float goal_x, goal_y;       // Goal coordinates
    uint32_t max_iterations;    // Maximum iterations for pathfinding
} TaskRequest;

/**
 * Task response structure sent by worker to master
 */
typedef struct {
    uint32_t task_id;           // Corresponding task_id
    uint32_t path_length;       // Number of waypoints in path
    float *path;                // Dynamically allocated path (pairs of x,y)
    uint32_t iterations_used;   // Actual iterations used
    int32_t status_code;        // 0 = success, negative = error
} TaskResponse;

/**
 * Generic message header
 */
typedef struct {
    uint32_t message_type;      // MessageType enum value
    uint32_t payload_size;      // Size of payload in bytes
    uint32_t sequence_number;   // For tracking message order
} MessageHeader;

/**
 * TCP Server context (used by master)
 */
typedef struct tcp_server tcp_server;

/**
 * TCP Client context (used by worker)
 */
typedef struct tcp_client tcp_client;

/* ============= SERVER SIDE (MASTER) ============= */

/**
 * Create and bind a TCP server on the specified port
 * Returns: pointer to server context, or NULL on error
 */
tcp_server* tcp_server_create(const char *host, uint16_t port, int backlog);

/**
 * Accept an incoming connection from a worker
 * Blocks until a connection is received
 * Returns: socket file descriptor for the connected client, or -1 on error
 */
int tcp_server_accept(tcp_server *server);

/**
 * Cleanup and close server socket
 */
void tcp_server_destroy(tcp_server **server);

/* ============= CLIENT SIDE (WORKER) ============= */

/**
 * Create a TCP client and connect to a server
 * Returns: pointer to client context, or NULL on connection failure
 */
tcp_client* tcp_client_create(const char *host, uint16_t port);

/**
 * Check if client is connected
 * Returns: 1 if connected, 0 otherwise
 */
int tcp_client_is_connected(tcp_client *client);

/**
 * Cleanup and close client connection
 */
void tcp_client_destroy(tcp_client **client);

/* ============= BIDIRECTIONAL (BOTH SIDES) ============= */

/**
 * Send a message over a connected socket
 * Returns: number of bytes sent, or -1 on error
 */
ssize_t tcp_send_message(int socket_fd, MessageType type, const void *payload, uint32_t payload_size);

/**
 * Receive a message from a connected socket
 * Allocates memory for payload; caller must free it
 * Returns: number of bytes received, or -1 on error
 */
ssize_t tcp_recv_message(int socket_fd, MessageHeader *header, void **out_payload);

/**
 * Send a task request from master to worker
 * Returns: 0 on success, -1 on error
 */
int tcp_send_task_request(int socket_fd, const TaskRequest *task);

/**
 * Receive a task request (worker side)
 * Allocates task structure; caller must free it
 * Returns: 0 on success, -1 on error
 */
int tcp_recv_task_request(int socket_fd, TaskRequest **out_task);

/**
 * Send a task response from worker to master
 * Returns: 0 on success, -1 on error
 */
int tcp_send_task_response(int socket_fd, const TaskResponse *response);

/**
 * Receive a task response (master side)
 * Allocates response structure with path array; caller must free both
 * Returns: 0 on success, -1 on error
 */
int tcp_recv_task_response(int socket_fd, TaskResponse **out_response);

/**
 * Send a shutdown signal
 * Returns: 0 on success, -1 on error
 */
int tcp_send_shutdown(int socket_fd);

/**
 * Free a TaskResponse structure and its payload
 */
void tcp_taskresponse_free(TaskResponse **response);

/**
 * Free a TaskRequest structure
 */
void tcp_taskrequest_free(TaskRequest **task);

#endif // TCP_H
