#include "tcp.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>

// This file was generated by Claude Haiku 4.5.

/* ============= STRUCTURES ============= */

struct tcp_server {
    int socket_fd;
    uint16_t port;
    struct sockaddr_in server_addr;
};

struct tcp_client {
    int socket_fd;
    uint16_t port;
    char host[256];
    int connected;
};

/* ============= UTILITY FUNCTIONS ============= */

/**
 * Set socket to non-blocking or blocking mode
 */
static int set_nonblocking(int socket_fd, int nonblocking)
{
    int flags = fcntl(socket_fd, F_GETFL, 0);
    if (flags < 0) return -1;
    if (nonblocking) {
        flags |= O_NONBLOCK;
    } else {
        flags &= ~O_NONBLOCK;
    }
    return fcntl(socket_fd, F_SETFL, flags);
}

/**
 * Set TCP_NODELAY to disable Nagle's algorithm for lower latency
 */
static int set_tcp_nodelay(int socket_fd)
{
    int flag = 1;
    return setsockopt(socket_fd, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof(flag));
}

/**
 * Ensure all data is sent over socket
 */
static ssize_t send_all(int socket_fd, const void *data, size_t len)
{
    size_t total_sent = 0;
    const uint8_t *buf = (const uint8_t *)data;

    while (total_sent < len) {
        ssize_t sent = send(socket_fd, buf + total_sent, len - total_sent, 0);
        if (sent < 0) {
            perror("send");
            return -1;
        }
        if (sent == 0) {
            fprintf(stderr, "Connection closed by peer during send\n");
            return -1;
        }
        total_sent += sent;
    }
    return total_sent;
}

/**
 * Ensure all data is received from socket
 */
static ssize_t recv_all(int socket_fd, void *data, size_t len)
{
    size_t total_recv = 0;
    uint8_t *buf = (uint8_t *)data;

    while (total_recv < len) {
        ssize_t received = recv(socket_fd, buf + total_recv, len - total_recv, 0);
        if (received < 0) {
            perror("recv");
            return -1;
        }
        if (received == 0) {
            fprintf(stderr, "Connection closed by peer during recv\n");
            return -1;
        }
        total_recv += received;
    }
    return total_recv;
}

/* ============= SERVER SIDE (MASTER) ============= */

tcp_server* tcp_server_create(const char *host, uint16_t port, int backlog)
{
    tcp_server *server = (tcp_server *)malloc(sizeof(tcp_server));
    if (!server) {
        perror("malloc");
        return NULL;
    }

    server->socket_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (server->socket_fd < 0) {
        perror("socket");
        free(server);
        return NULL;
    }

    // Enable address reuse
    int reuse = 1;
    if (setsockopt(server->socket_fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse)) < 0) {
        perror("setsockopt");
        close(server->socket_fd);
        free(server);
        return NULL;
    }

    // Disable Nagle's algorithm
    if (set_tcp_nodelay(server->socket_fd) < 0) {
        fprintf(stderr, "Failed to set TCP_NODELAY\n");
    }

    memset(&server->server_addr, 0, sizeof(server->server_addr));
    server->server_addr.sin_family = AF_INET;
    server->server_addr.sin_port = htons(port);

    // Bind to all interfaces or specified host
    if (host && strlen(host) > 0) {
        if (inet_pton(AF_INET, host, &server->server_addr.sin_addr) <= 0) {
            fprintf(stderr, "Invalid host: %s\n", host);
            close(server->socket_fd);
            free(server);
            return NULL;
        }
    } else {
        server->server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    }

    if (bind(server->socket_fd, (struct sockaddr *)&server->server_addr, sizeof(server->server_addr)) < 0) {
        perror("bind");
        close(server->socket_fd);
        free(server);
        return NULL;
    }

    if (listen(server->socket_fd, backlog) < 0) {
        perror("listen");
        close(server->socket_fd);
        free(server);
        return NULL;
    }

    server->port = port;
    printf("Server listening on %s:%u\n", host ? host : "0.0.0.0", port);

    return server;
}

int tcp_server_accept(tcp_server *server)
{
    if (!server) return -1;

    struct sockaddr_in client_addr;
    socklen_t client_addr_len = sizeof(client_addr);

    int client_fd = accept(server->socket_fd, (struct sockaddr *)&client_addr, &client_addr_len);
    if (client_fd < 0) {
        perror("accept");
        return -1;
    }

    // Disable Nagle's algorithm for this client connection
    if (set_tcp_nodelay(client_fd) < 0) {
        fprintf(stderr, "Failed to set TCP_NODELAY on client socket\n");
    }

    char client_ip[INET_ADDRSTRLEN];
    inet_ntop(AF_INET, &client_addr.sin_addr, client_ip, INET_ADDRSTRLEN);
    printf("Accepted connection from %s:%u\n", client_ip, ntohs(client_addr.sin_port));

    return client_fd;
}

void tcp_server_destroy(tcp_server **server)
{
    if (!server || !*server) return;

    if ((*server)->socket_fd >= 0) {
        close((*server)->socket_fd);
    }
    free(*server);
    *server = NULL;
}

/* ============= CLIENT SIDE (WORKER) ============= */

tcp_client* tcp_client_create(const char *host, uint16_t port)
{
    if (!host) {
        fprintf(stderr, "host cannot be NULL\n");
        return NULL;
    }

    tcp_client *client = (tcp_client *)malloc(sizeof(tcp_client));
    if (!client) {
        perror("malloc");
        return NULL;
    }

    client->socket_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (client->socket_fd < 0) {
        perror("socket");
        free(client);
        return NULL;
    }

    // Disable Nagle's algorithm
    if (set_tcp_nodelay(client->socket_fd) < 0) {
        fprintf(stderr, "Failed to set TCP_NODELAY\n");
    }

    struct sockaddr_in server_addr;
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(port);

    if (inet_pton(AF_INET, host, &server_addr.sin_addr) <= 0) {
        fprintf(stderr, "Invalid host: %s\n", host);
        close(client->socket_fd);
        free(client);
        return NULL;
    }

    if (connect(client->socket_fd, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0) {
        perror("connect");
        close(client->socket_fd);
        free(client);
        return NULL;
    }

    client->port = port;
    strncpy(client->host, host, sizeof(client->host) - 1);
    client->host[sizeof(client->host) - 1] = '\0';
    client->connected = 1;
    printf("Connected to server at %s:%u\n", host, port);

    return client;
}

int tcp_client_is_connected(tcp_client *client)
{
    return client && client->connected;
}

void tcp_client_destroy(tcp_client **client)
{
    if (!client || !*client) return;

    if ((*client)->socket_fd >= 0) {
        close((*client)->socket_fd);
    }
    (*client)->connected = 0;
    free(*client);
    *client = NULL;
}

/* ============= BIDIRECTIONAL (BOTH SIDES) ============= */

ssize_t tcp_send_message(int socket_fd, MessageType type, const void *payload, uint32_t payload_size)
{
    if (socket_fd < 0) return -1;

    MessageHeader header;
    memset(&header, 0, sizeof(header));
    header.message_type = (uint32_t)type;
    header.payload_size = payload_size;
    header.sequence_number = 0;  // Could be incremented per connection

    // Send header
    if (send_all(socket_fd, &header, sizeof(header)) < 0) {
        return -1;
    }

    // Send payload
    if (payload_size > 0 && payload) {
        if (send_all(socket_fd, payload, payload_size) < 0) {
            return -1;
        }
    }

    return sizeof(header) + payload_size;
}

ssize_t tcp_recv_message(int socket_fd, MessageHeader *header, void **out_payload)
{
    if (socket_fd < 0 || !header || !out_payload) return -1;

    // Receive header
    if (recv_all(socket_fd, header, sizeof(MessageHeader)) < 0) {
        return -1;
    }

    // Allocate and receive payload
    *out_payload = NULL;
    if (header->payload_size > 0) {
        *out_payload = malloc(header->payload_size);
        if (!*out_payload) {
            perror("malloc");
            return -1;
        }

        if (recv_all(socket_fd, *out_payload, header->payload_size) < 0) {
            free(*out_payload);
            *out_payload = NULL;
            return -1;
        }
    }

    return sizeof(MessageHeader) + header->payload_size;
}

int tcp_send_task_request(int socket_fd, const TaskRequest *task)
{
    if (!task) return -1;

    ssize_t sent = tcp_send_message(socket_fd, MSG_TASK_REQUEST, (void *)task, sizeof(TaskRequest));
    return (sent > 0) ? 0 : -1;
}

int tcp_recv_task_request(int socket_fd, TaskRequest **out_task)
{
    if (!out_task) return -1;

    MessageHeader header;
    void *payload = NULL;

    if (tcp_recv_message(socket_fd, &header, &payload) < 0) {
        return -1;
    }

    if (header.message_type != MSG_TASK_REQUEST) {
        fprintf(stderr, "Expected MSG_TASK_REQUEST, got %u\n", header.message_type);
        free(payload);
        return -1;
    }

    if (header.payload_size != sizeof(TaskRequest)) {
        fprintf(stderr, "Invalid task request payload size: %u\n", header.payload_size);
        free(payload);
        return -1;
    }

    *out_task = (TaskRequest *)payload;
    return 0;
}

int tcp_send_task_response(int socket_fd, const TaskResponse *response)
{
    if (!response) return -1;

    // Send header with response metadata
    uint32_t path_bytes = response->path_length * sizeof(float) * 2;
    uint32_t response_header_size = sizeof(uint32_t) * 3 + sizeof(int32_t);  // task_id, path_length, iterations_used, status_code
    uint32_t total_payload = response_header_size + path_bytes;

    // Pack response data
    uint8_t *payload = (uint8_t *)malloc(total_payload);
    if (!payload) {
        perror("malloc");
        return -1;
    }

    uint8_t *ptr = payload;
    *(uint32_t *)ptr = response->task_id;
    ptr += sizeof(uint32_t);
    *(uint32_t *)ptr = response->path_length;
    ptr += sizeof(uint32_t);
    *(uint32_t *)ptr = response->iterations_used;
    ptr += sizeof(uint32_t);
    *(int32_t *)ptr = response->status_code;
    ptr += sizeof(int32_t);

    if (response->path_length > 0 && response->path) {
        memcpy(ptr, response->path, path_bytes);
    }

    ssize_t sent = tcp_send_message(socket_fd, MSG_TASK_RESPONSE, payload, total_payload);
    free(payload);

    return (sent > 0) ? 0 : -1;
}

int tcp_recv_task_response(int socket_fd, TaskResponse **out_response)
{
    if (!out_response) return -1;

    MessageHeader header;
    void *payload = NULL;

    if (tcp_recv_message(socket_fd, &header, &payload) < 0) {
        return -1;
    }

    if (header.message_type != MSG_TASK_RESPONSE) {
        fprintf(stderr, "Expected MSG_TASK_RESPONSE, got %u\n", header.message_type);
        free(payload);
        return -1;
    }

    // Unpack response data
    TaskResponse *response = (TaskResponse *)malloc(sizeof(TaskResponse));
    if (!response) {
        perror("malloc");
        free(payload);
        return -1;
    }

    uint8_t *ptr = (uint8_t *)payload;
    response->task_id = *(uint32_t *)ptr;
    ptr += sizeof(uint32_t);
    response->path_length = *(uint32_t *)ptr;
    ptr += sizeof(uint32_t);
    response->iterations_used = *(uint32_t *)ptr;
    ptr += sizeof(uint32_t);
    response->status_code = *(int32_t *)ptr;
    ptr += sizeof(int32_t);

    // Allocate and copy path
    if (response->path_length > 0) {
        uint32_t path_bytes = response->path_length * sizeof(float) * 2;
        response->path = (float *)malloc(path_bytes);
        if (!response->path) {
            perror("malloc");
            free(response);
            free(payload);
            return -1;
        }
        memcpy(response->path, ptr, path_bytes);
    } else {
        response->path = NULL;
    }

    free(payload);
    *out_response = response;
    return 0;
}

int tcp_send_shutdown(int socket_fd)
{
    ssize_t sent = tcp_send_message(socket_fd, MSG_SHUTDOWN, NULL, 0);
    return (sent > 0) ? 0 : -1;
}

void tcp_taskresponse_free(TaskResponse **response)
{
    if (!response || !*response) return;

    if ((*response)->path) {
        free((*response)->path);
        (*response)->path = NULL;
    }
    free(*response);
    *response = NULL;
}

void tcp_taskrequest_free(TaskRequest **task)
{
    if (!task || !*task) return;
    free(*task);
    *task = NULL;
}
